### ISSUE TITLE
Differentiate between rng used for noise and rng used to sample pseudorandom polynomials + Add seeded types

### ISSUE THREAD

**Issue by Janmajayamall** [gausslabs/phantom-zone#23]
Modify key generation / encryption functions to accept two type of RNGs `p_rng` and `rng`. `p_rng` is used to sample pseudo randomly generated polynomials (for example, part `a` of RLWE ciphertext encrypted with secret key). `rng` is used to sample noise polynomials. This comes handy to generate key shares for MPC protocols using common reference seed.

**Comment by Janmajayamall** [comment]
@han0110

**Comment by han0110** [comment]
Implemented in #32
